name = "ROCr"
uuid = "9f942a60-f134-4a3a-961a-62da239d23fb"
authors = ["Julian P Samaroo <jpsamaroo@jpsamaroo.me>"]
version = "0.3.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
CEnum = "0.2"
Setfield = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
